image: alpine/latest
packages:
        - texinfo
sources:
        - https://git.sr.ht/~dsemy/swsw
tasks:
        - build: |
                cd swsw
                make
artifacts:
        - swsw/swsw-2.3.tar
