stages:
  - build
  - release

package:
  stage: build
  image: silex/emacs:29
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev | sh
    - export PATH=$PATH:/root/.local/bin
  script:
    - eldev lint doc re
    # TODO package-lint erroneously says emacs 26 doesn't support org-collect-keywords
    # - eldev lint package
    - eldev compile -W
    - eldev test
    - eldev package
  artifacts:
    paths:
      - dist/

release:
  stage: release
  only:
    - tags
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - package
  variables:
    DIST_DIR: $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/dist
    FILENAME_BASE: $CI_PROJECT_NAME-$CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    description: $CI_COMMIT_DESCRIPTION
    assets:
      links:
        - name: $FILENAME_BASE.el
          url: $DIST_DIR/$FILENAME_BASE.el
  script:
    - echo Release job
  artifacts:
    paths:
      - dist/
    expire_in: never
