name: Changelog
on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: trevorpogue
          repo: topspace
          base: HISTORY.md
